linters-settings:
    gci:
        local-prefixes: github.com/sagikazarmark/viperx
    goimports:
        local-prefixes: github.com/sagikazarmark/viperx
    golint:
        min-confidence: 0

linters:
    disable-all: true
    enable:
        - bodyclose
        - deadcode
        - dogsled
        - dupl
        - errcheck
        - exhaustive
        - exportloopref
        - gci
        - gochecknoglobals
        - gochecknoinits
        - gocognit
        - goconst
        - gocritic
        - gocyclo
        - godot
        - gofmt
        - gofumpt
        - goimports
        - golint
        - goprintffuncname
        - gosec
        - gosimple
        - govet
        - ifshort
        - ineffassign
        - lll
        - makezero
        - misspell
        - nakedret
        - nlreturn
        - noctx
        - nolintlint
        - prealloc
        - predeclared
        - revive
        - rowserrcheck
        - scopelint
        - sqlclosecheck
        - staticcheck
        - structcheck
        - stylecheck
        - thelper
        - tparallel
        - typecheck
        - unconvert
        - unparam
        - unused
        - varcheck
        - whitespace

        # unused
        # - depguard
        # - goheader
        # - gomodguard

        # don't enable:
        # - asciicheck
        # - exhaustivestruct
        # - forbidigo
        # - funlen
        # - godox
        # - goerr113
        # - gomnd
        # - interfacer
        # - maligned
        # - nestif
        # - paralleltest
        # - testpackage
        # - wrapcheck
        # - wsl
